spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deadcow5
    username: leesoobeen
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue.name: sample.queue
  exchange.name: sample.exchange
  routing.key: sample.deadcow5

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

slack:
  token: xoxb-4683572787793-5810479436674-jhgRIRWcHgAkmKNBlthAc8xN
